name: publish-plugin
run-name: Publish
permissions:
  contents: write
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  build:
    name: Publish plugin
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: modified
    - name: Build
      shell: bash
      run: git archive --format=zip --prefix="fast-velocity-minify/" HEAD > ${{ github.workspace }}/fast-velocity-minify.zip
    - name: Upload zip file to GitHub actions artifact
      uses: actions/upload-artifact@v4
      with:
        name: fast-velocity-minify.zip
        path: ${{ github.workspace }}/fast-velocity-minify.zip
    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        files: fast-velocity-minify.zip
        body: Release ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
